
apiVersion: v1
kind: ConfigMap
metadata:
  name: funiture-config
  namespace: furniture
data:
  MONGODB_URI: "mongodb://mongo-service:27017/furniture"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://13.232.97.144/api"
  NEXTAUTH_URL: "https://13.232.97.144/"
  NEXTAUTH_SECRET: "0xc9u7nNqm1XTQ7RfH83vWOnMJT+h92jjpfoGNJQztQ="
  JWT_SECRET: "719a61f58d82de030088d02545f6b31a3ebacba600fe96deecbd562ff27e191f"
