apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: furniture-ingress
  namespace: furniture
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: "3.109.154.215.nip.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: furniture-service
            port:
              number: 80
